//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTask
    {
        public int ID { get; set; }
        public string Student_ID { get; set; }
        public int Task_ID { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Task Task { get; set; }
    }
}
