//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int ID { get; set; }
        public int Task_ID { get; set; }
        public int Group_ID { get; set; }
        public int Subject_ID { get; set; }
        public System.DateTime DeadLine { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Task Task { get; set; }
    }
}
