//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersGroup
    {
        public int ID { get; set; }
        public string Teacher_ID { get; set; }
        public int Group_ID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Group Group { get; set; }
    }
}
